### ISSUE TITLE
node-controller: increase intitial delay for healthcheck

### ISSUE THREAD

**Issue by calvix** [giantswarm/kvm-operator#344]
When we create a new cluster,  node-controller is restarted about 6 times because k8s-api is not yet ready.

We should set initial health check delay to 1 or 2 minutes to avoid this.

cc @r7vme

**Comment by r7vme** [comment]
ack. As issue not really affects any functionality, i'll take look on it with lower priority.

Problem here that we can not prevent restart at all, because node-controller [aggregates all errors](https://github.com/giantswarm/kvm-operator-node-controller/blob/master/controller.go#L139-L142) and if error count is not 0 (which will be not zero) it will be restarted anyway.

We can only assume that master provisioning always takes ~3 minutes, so we can put this number into initial delay.

**Comment by calvix** [comment]
Yeah, agree
